"""empty message

Revision ID: 7c49292b354d
Revises: 
Create Date: 2024-05-28 13:24:32.294818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c49292b354d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questionnaire_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('score', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questionnaire_data', schema=None) as batch_op:
        batch_op.drop_column('score')

    # ### end Alembic commands ###
