"""empty message

Revision ID: ebdf5cdf12f7
Revises: 7c49292b354d
Create Date: 2024-05-29 21:57:16.985868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebdf5cdf12f7'
down_revision = '7c49292b354d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('coaches', 'availability',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('coaches', 'availability',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
